name: Auto-resolve PR conflicts for Codex branches

on:
  pull_request:
    types: [opened, synchronize]  # при создании PR и при пушах в неё
    branches: [ main ]           # целевая ветка — main

jobs:
  resolve-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          # снимаем всё, чтобы можно было мёржить
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into PR branch (theirs)
        run: |
          # Забираем свежий main
          git fetch origin main
          # Мёржим его в текущую ветку (Codex-ветку)
          git merge origin/main -s recursive -X theirs --no-edit

      - name: Push resolved branch
        run: |
          git push origin HEAD:${{ github.head_ref }}

